package messenger

import (
	"fmt"
	"time"

	"github.com/stevenxie/begone/strgen"
	"github.com/tebeka/selenium"
)

const (
	ifSelector = "div.notranslate._5rpu" // input field classname
)

// Spam spams the target conversation with messages generated by 'g' (a
// strgen.Generator) reps times.
//
// If reps < 0, Spam will continue indefinitely.
func (e *Engine) Spam(g strgen.Generator, reps int) error {
	if e.wd == nil {
		e.Login()
	}

	if url, err := e.wd.CurrentURL(); err != nil {
		return fmt.Errorf("messenger: error getting current URL: %v", err)
	} else if url != e.MessengerURL() { // still on login page
		e.Login()
	}

	// Attempt to focus on input field (may cause a page refresh).
	if _, err := getInputField(e.wd); err != nil {
		return err
	}

	// Get input field after page refresh.
	inf, err := getInputField(e.wd)
	if err != nil {
		return err
	}

	// Begin spamming.
	startTime := time.Now()
	for g.HasMore() {
		if reps >= 0 {
			if reps == 0 {
				break
			}
			reps--
		}

		if err = inf.SendKeys(g.Generate()); err != nil {
			return fmt.Errorf("messenger: failed to send keys while spamming: %v",
				err)
		}

		if err := inf.SendKeys(selenium.EnterKey); err != nil {
			return fmt.Errorf("messenger: failed to send enter key while "+
				"spamming: %v", err)
		}

		// Prevent Facebook from getting too suspicious (ensure 100ms have passed).
		diff := time.Now().Sub(startTime)
		if diff.Nanoseconds() < 1000000 {
			time.Sleep(startTime.Add(10 * time.Millisecond).Sub(time.Now()))
		}
	}

	return nil
}

// Wait for, click on, and return input field.
func getInputField(wd selenium.WebDriver) (selenium.WebElement, error) {
	if err := wd.Wait(func(wdd selenium.WebDriver) (bool, error) {
		_, err := wdd.FindElement(selenium.ByCSSSelector, ifSelector)
		return err == nil, err
	}); err != nil {
		return nil, fmt.Errorf("messenger: error while waiting for input field: %v",
			err)
	}

	inf, err := wd.FindElement(selenium.ByCSSSelector, ifSelector)
	if err != nil {
		return nil, fmt.Errorf("messenger: error finding input field: %v", err)
	}

	if err = wd.Click(selenium.LeftButton); err != nil {
		return nil, fmt.Errorf("messenger: error clicking input field: %v", err)
	}

	return inf, nil
}
