#!/usr/bin/env bash

## [GO MOD DEPS]
dl() {
  echo # visual separator

  if ! command -v make >/dev/null 2>&1; then
    echo "Could not download dependencies with 'make dl'; GNU make not found." >&2
    return 1
  fi

  make dl || return $?
}
dl || exit $?
